### ISSUE TITLE
PDF's mirrored

### ISSUE THREAD

**Issue by ArnoutVerbeken** [NebraLtd/nebra-lora-hardware#1]
It seems that all PDF's (at least those that I checked) are mirrored.

Here are some examples:
https://github.com/NebraLtd/nebra-lora-hardware/blob/master/Smart-Indoor-Mainboard-V1/HARDWARE/indoor-schematic.pdf

https://github.com/NebraLtd/nebra-lora-hardware/blob/master/Smart-Outdoor-Mainboard-V1/HARDWARE/Pi%20Supply%20Smart%20LoRa%20Gateway-back.pdf

I think a PDF "that is readable" is more appropriate here.

**Comment by shawaj** [comment]
@ryanteck could you take a look and provide the non-mirror-image PDFs?

**Comment by ryanteck** [comment]
I believe this is now fixed.

**Comment by ryanteck** [comment]
I've re-uploaded them all unmirrored, plus I noticed on a few only 1 out of multiple pages generated.

All now uploaded and corrected.

The only one that hasn't changed is the outdoor gateway back as this is intended to be mirrored. The front is the non mirrored version.

**Comment by shawaj** [comment]
👍 thanks @ryanteck
