### ISSUE TITLE
Gl5712 U schematic help, missing components

### ISSUE THREAD

**Issue by serbyxp** [NebraLtd/nebra-lora-hardware#8]
![7186A464-28E2-42A8-AAD0-FB9B3FBC94FB](https://user-images.githubusercontent.com/73319313/145444855-b454d8bc-3069-4965-bd64-88e3995bdd03.jpeg)
I have an issue I’m not sure if this is supposed to be different then the photos in the “internal photos .pdf.  But next to the uFL connector on the mpcie concentrator board maxiiot GL5712-U on the right hand side of the connector I see in the photo that there are wht looks like smd capacitors / diodes… on my miner I am not seeing the blue smd component.  I am not sure if this is normal or not. But I need to know if there is a schematic. Or components list for the US 915 variant . I am having issues with the miner recently not sure if it over heated or what? And if that’s even important for the operation of the miner/ hotspot.

thank you

**Comment by vpetersson** [comment]
This is not a support forum. Please contact [support@nebra.com](mailto:support@nebra.com).
